#!/usr/bin/env python

from __future__ import print_function

from pprint import pprint
import collections
import os
import sys
import re

csv_files = sys.argv[1:]

# given the CSV files, print a data dictionary

# dictionary format should be:
# LIBRARIES = {
#     'sample_1_unique_id': {
#         'track_name' : '...',
#         'bedgraph' : '...',
#         'genome' : '...',
#         'macs2_out' : '...',
#         'peaks' : '...',
#     },
#     'sample_2_unique_id' ....
# }


def csv_file_to_sequencing_run(f):
    return re.match('Run_(\d+).csv', os.path.basename(csv_file)).groups(0)[0]


def lane_to_readgroup_name(lane):
    return 'L{:03d}'.format(lane)


def bedgraph_path(seqcore_id):
    atacseq_processing_dir = os.path.join(os.getenv('DANFORTH_HOME'), 'work', 'atacseq', 'results')
    return os.path.join(atacseq_processing_dir, 'macs2', '{}_treat_pileup.bdg'.format(seqcore_id))


def peak_path(seqcore_id):
    atacseq_processing_dir = os.path.join(os.getenv('DANFORTH_HOME'), 'work', 'atacseq', 'results')
    return os.path.join(atacseq_processing_dir, 'macs2', '{}_peaks.broadPeak.noblacklist'.format(seqcore_id))


def macs2_out_path(seqcore_id):
    atacseq_processing_dir = os.path.join(os.getenv('DANFORTH_HOME'), 'work', 'atacseq', 'results')
    return os.path.join(atacseq_processing_dir, 'macs2', '{}.macs2.out'.format(seqcore_id))


LIBRARIES = {}

for csv_file in csv_files:

    header_line = None
    sequencing_run = csv_file_to_sequencing_run(csv_file)

    with open(csv_file, 'r') as f:
        for line in f:
            line_l = line.rstrip().split(',')
            if header_line is None:
                if line_l[0] == 'Lane':
                    header_line = line
                    continue
                else:
                    continue

            parsed_line = dict(zip(header_line.split(','), line_l))  # e.g. d['Lane'] --> 1, d['Sample_ID'] = 'Sample_90470' ...

            seqcore_id = parsed_line['Sample_ID'].replace('Sample_', '')
            unique_id = seqcore_id
            genome = 'mm9'

            if unique_id not in LIBRARIES:
                sample_information = {
                    'genome': genome,
                    'bedgraph': bedgraph_path(seqcore_id),
                    'macs2_out': macs2_out_path(seqcore_id),
                    'peaks': peak_path(seqcore_id)
                }

                LIBRARIES[unique_id] = sample_information


# now print the dictionary
LIBRARIES = collections.OrderedDict(sorted(LIBRARIES.items()))
pprint(dict(LIBRARIES.items()), width=1)
